### ISSUE TITLE
ioshelper name

### ISSUE THREAD

**Issue by marinofaggiana** [rullzer/ioshelper#3]
it's not good

**Comment by rullzer** [comment]
Suggestions are welcome

**Comment by marinofaggiana** [comment]
can be listPaginationProvider

**Comment by rullzer** [comment]
That is not making it any easier for anybody to guess what it does.

**Comment by marinofaggiana** [comment]
it is not necessary, it should be system, practically anyone who uses iOS "Files" has problems, in addition to the incredible and unnecessary network overload when list a directory

**Comment by rullzer** [comment]
name changed
