### ISSUE TITLE
Parameter request

### ISSUE THREAD

**Issue by marinofaggiana** [rullzer/ioshelper#4]
Please add the order by and ascending descending

**Comment by rullzer** [comment]
I don't think I can just have you sort by anything. What are the parameters that are most needed?

**Comment by marinofaggiana** [comment]
The order of iOS "Files" can be: Namefile, date, dimension, contentype => (asc, disc)

**Comment by rullzer** [comment]
dimension? you mean size?

**Comment by marinofaggiana** [comment]
yes yes

**Comment by rullzer** [comment]
Ok you can now pass

* sort
  - name (default fallback if none provided or invalid one provided)
  - size
  - mtime
  - mimetype
* order
  - asc (default fallback if none provided or invalid one provided)
  - desc
