### ISSUE TITLE
First item / compatibility

### ISSUE THREAD

**Issue by marinofaggiana** [rullzer/ioshelper#5]
For compatibility with the "normal" PROPFIND the first item is the current directory item, for example for the "/hello" the first item is the data of directory hello (for detail look the PROPFIND response.

**Note: this is indispensable**

**Comment by rullzer** [comment]
Then we would have to switch to having the full path. And not just the name. Else you can't distrinquis

**Comment by marinofaggiana** [comment]
sure ! + order

**Comment by marinofaggiana** [comment]
@rullzer I would like to close this .... thx

**Comment by rullzer** [comment]
ok path is now also added
